- APIs/OData.md
Refresh token should be mentioned, for front-end applications is important the usage of this token to avoid exposing user credentials as this refresh token can be stored in the state of the app besides the user and password credentials that should be stored always on the backend.
> Refresh token

- APIs/OpenSearch.md
DAS-333 add Product Download section in OpenSearch API
> DAS-333 Product Download in OpenSearch API

- Token.qmd
- _quarto.yml
> token page added CDAS-607

- .gitignore
- Roadmap/APITable.qmd
- Roadmap/AppTable.qmd
- Roadmap/DataTable.qmd
- Roadmap/DataTableold.qmd
spelling check and correct the roadmap view
> data roadmap view

- APIs/Traceability.md
- _quarto.yml
Add traceability doc with link update
> Traceability doc

- Applications/Browser.md
This PR fixes a few rendering and description errors in the Browser documentation page.
> Update browser docs images

- .github/workflows/pr-publish.yml
- .gitmodules
- _quarto.yml
@soxofaan @Pratichhya @JanssenBrm 
test PR to experiment with rendering our notebooks as part of the documentation, to enable search, and also give more visbility to our notebooks.
> also render sample notebooks

- Data/collections.json
> updated offer table

- custom.css
Updated hyperlink color from #FABC20 to #0A4393
> updated hyperlink color

- APIs/S3.md
- update S3 endpoint
- update S3 path from DIAS to eodata
> Update S3 doc

- APIs/Traceability.md
- update description
- update links
> Update Traceability doc

- Roadmap.md
service description pdf is updated on 01/08/2023 and delivered to us for updating
> updated service description pdf

- Data/collections.json
updated collections.json to add HH and HV to S1GRD on" [/Data/Sentinel1.html](https://documentation.dataspace.copernicus.eu/Data/Sentinel1.html) Further details about the data collection"
> updated collectionsjson to add HH and HV to S1GRD

- APIs/openEO/Glossary.qmd
In line with the baseline document available in https://openeo.org/documentation/1.0/glossary.html#eo-data-collections 
except for the data processing modes.
> Improved glossary

- _quarto.yml
Include a usecase example of rank composite within the openEO notebook notebook examples.
> included rank composite example

- Applications/PlazaDetails/ManageBilling.qmd
- Quotas.qmd
As of last release, we have updated the number of free credtis to 3000. This should also be reflected in the documentation.
> docs: updated number of free credits to 3000

- APIs/On-Demand Production API.md
fixed urlencoding in curl requests
fixed errors in url
> Update On-Demand Production API.md

- APIs/OData.qmd
- APIs/OpenSearch.qmd
- APIs/STAC.qmd
Update of STAC documentation. Adding Global-Mosaics collections to OData, STAC and OpeanSearch API description. Links update within APIs documentation.
> Stac doc update

- APIs/OpenSearch.qmd
> update OpenSearch doc

- APIs/STAC.qmd
> update STAC doc

- APIs/OData.qmd
> update OData doc

- _quarto.yml
Included a notebook for parcel delineation when using openEO from its community examples list.
> Parcel Delination notebook

- Data/SentinelMissions/Sentinel1.qmd
updating documentation to highlight the steps/workaround involved in addressing the issue when processing/downloading Sentinel-1 data as suggested in https://github.com/Open-EO/openeo-geopyspark-driver/issues/311.
> Sar backscatter include

- APIs/SentinelHub/ApiReference/openapi.v1.yaml
- APIs/SentinelHub/BatchStatistical.qmd
- APIs/SentinelHub/Data/S1GRD.qmd
- APIs/SentinelHub/Data/S2L1C.qmd
- APIs/SentinelHub/Data/S3OLCI.qmd
- APIs/SentinelHub/Data/S3SLSTR.qmd
- APIs/SentinelHub/Data/S5PL2.qmd
- APIs/SentinelHub/OGC/WFS.qmd
- APIs/SentinelHub/Overview/ProcessingUnit.qmd
- APIs/SentinelHub/Statistical.qmd
Sync with latest Sentinel Hub documentation
> Sync with Sentinel Hub documentation

- .github/workflows/pr-publish.yml
Simply updated quarto version to old version to check if it address two titles issue
> specified quarto version

- APIs/SentinelHub/OGC/WFS.qmd
Removed non-CDSE collections and their respective footnotes. Removed AWS mention from table
> Remove non-CDSE data collections and footnotes

- APIs/OData.qmd
> update of odata doc

- Applications/AlgorithmPlaza.qmd
- Applications/PlazaDetails/ExecuteService.qmd
- Applications/PlazaDetails/ManageOrg.qmd
- Applications/PlazaDetails/ManageService.qmd
- Applications/PlazaDetails/PublishService.qmd
Removed extra alias from the openEO algorithm plaza
> removed extra alias

- Usecase.qmd
* changed display to image and title only
* added RVI
> Updated in Usecase qmd file

- APIs/openEO/openEO.qmd
- Usecase.qmd
This PR adds the best available pixel composite notebook to our documentation.
This also marks completion of an openEO roadmap item.
> best available pixel notebook

- Usecase.qmd
> new Usecase

- _quarto.yml
catalog csv app was shown at top level ot contents, this commit moves it next to all other applications
> Move catalog csv away from top level

- Roadmap.md
when u click on the tab where this doc opens - it refers to "Angebot für Eumetsat" => remove and replace this in the word document properties - info - title
> roadmap_pdf_remove_eumetsat_from_title

- Usecase.qmd
Included disaster usecase section
> Disater usecase

- Data/collections.json
With respect to Support ticket 2911
> renamed title

- APIs/openEO/R_Client/R.qmd
Updated the content. Examples are also working, except sometimes encountering 401 Authorisation error though logged in.
> Openeo Rclient

- Applications/Browser.qmd
Reported in https://jira.cloudferro.com/browse/CDSE-1367
> Broken sign-up link in About the Browser documentation

- .pre-commit-config.yaml
(redo of #614)
Some simple additions to pre-commit config (whitespace cleanups and some basic file format checks) so that users of that tool get some quality control at commit time
> Add some basic fixup hooks to pre-commit config

- _quarto.yml
> Issue #617 fix detection of "internal" links with link-external-filter config

- APIs/openEO/Python_Client/Python.qmd
- APIs/openEO/authentication.qmd
- _quarto.yml
Take 2 of PR #613  (targeting the publish branch this time)
(internal ref  eu-cdse/openeo-cdse-infra#233)
> Document machine-to-machine auth options in openeo
